### ISSUE TITLE
[BUG] instant dc if you do /ignorelist

### ISSUE THREAD

**Issue by Sand-Turtle** [ttRMS/ttRMS-support#12]
## Describe the bug

title ^

## How to cause this bug?

do /ignorelist

## What is supposed to happen?

not dc lol
## Screenshots

(screenshots can be pasted directly into this text box)

## Additional comments
javaoutofboundsarray 1 or something probably same bug as death msgs dc

**Comment by tycrek** [comment]
This is fixed in v1.2
