### ISSUE TITLE
[BUG] Dropped items do not render when dropped

### ISSUE THREAD

**Issue by lifetorrent** [ttRMS/ttRMS-support#13]
## Describe the bug

When logging into 2b while connected to the proxy, items dropped on the ground do not render (with/without NoRender on). Toggling NoRender appears to fix this temporarily for the session, but once I relog again the issue comes back. 

## How to cause this bug?

1. Log into 2b with NoRender enabled (items turned on so that they _should_ render)
2. Drop an item on the ground

## What is supposed to happen?

Items should render normally. 

## Screenshots

https://streamable.com/uqqi9w

**Comment by ToxicAven** [comment]
This is a known issue, but the cause is unknown.

**Comment by tycrek** [comment]
Motorway Extension Guru's recently confirmed in our technical channels to be an issue with 2b2t itself, as this has been noticed by some users when connecting directly with no proxy.

**There is speculation that it is more common when using a proxy,** however there's not enough data to confirm this.
