### ISSUE TITLE
[FEATURE] turn off receiving messages for certain discord managers

### ISSUE THREAD

**Issue by Sand-Turtle** [ttRMS/ttRMS-support#17]
## Describe the feature

let you toggle messages off in discord dms for certain users because of privacy. maybe also in the proxy as well in the same way restricting chat would work

## Why is this feature helpful

keep sensitive messages from being sent to certain users

## Screenshots

(screenshots can be pasted directly into this text box)

## Additional comments
this could be added in tandem with https://github.com/ttRMS/ttRMS-support/issues/15

**Comment by tycrek** [comment]
This has been added as "Mailman Secret" mode
