### ISSUE TITLE
[FEATURE] scheduled DC in addtion to joininh

### ISSUE THREAD

**Issue by Sand-Turtle** [ttRMS/ttRMS-support#18]
## Describe the feature

This feature will let you automatically dc your proxy without having it reconnect after a specified amount of time

## Why is this feature helpful

This feature would be helpful for players who want to travel/pave/dig a few hours and then automatically log off

## Screenshots

(screenshots can be pasted directly into this text box)

**Comment by tycrek** [comment]
This is already planned for upcoming AutoQueue overhaul so I will close this Issue
