### ISSUE TITLE
[BUG]disconnect from horse causes purgatory

### ISSUE THREAD

**Issue by Sand-Turtle** [ttRMS/ttRMS-support#19]
## Describe the bug
mounting a horse then exiting the server will make 2b unplayabled until you relog

## How to cause this bug?

1. mount horse
2. press disconnect
3. connect again

## What is supposed to happen?

I expected it to...

## Screenshots

(screenshots can be pasted directly into this text box)

**Comment by tycrek** [comment]
most likely caching issue

**Comment by tycrek** [comment]
fixed
