### ISSUE TITLE
[BUG] when extrachat is enabled chat is delayed by a few seconds

### ISSUE THREAD

**Issue by Sand-Turtle** [ttRMS/ttRMS-support#20]
## Describe the bug

title ^

## How to cause this bug?

1. enable extrachat
2. try to type in chat
3. it will be delayed from 1.5-5 seconds

## What is supposed to happen?

I expected it to...

## Screenshots

(screenshots can be pasted directly into this text box)

https://2b2t.lgbt/​​​​​‍‍⁠‌‍‍​

**Comment by tycrek** [comment]
will look into it

**Comment by tycrek** [comment]
I'm unable to reproduce this, closing
