### ISSUE TITLE
[FEATURE] auto-ignore/ignorehard

### ISSUE THREAD

**Issue by Sand-Turtle** [ttRMS/ttRMS-support#24]
## Describe the feature

will let you ignore people automatically based on filters. it can be limited to dms, be for global chat too, toggle between /ignore and /ignorehard. maybe a ignorelist you can export to other instances

## Why is this feature helpful

automatically block spam bots such as the worse ones aka 2b2t.shop
## Screenshots

https://user-images.githubusercontent.com/79060069/127243623-a5674ab7-a5ed-44cb-9493-de92d574cb0a.mp4

**Comment by tycrek** [comment]
AntiChat has been patched to block Discord forwarding
