### ISSUE TITLE
[FEATURE] api for controlling proxy

### ISSUE THREAD

**Issue by czho** [ttRMS/ttRMS-support#6]
## Describe the feature

A way to edit settings, and control the proxy thru code, not having to be connected to it on a mc account, or thru discord.

## Why is this feature helpful

Making scripts for having multiple prio accounts joining at the same time. It would also make skynet integration way easier, I wouldnt have to code a hacked together discord bot just to control it.

## Additional comments

The best solution would probably be rustful(I think I'm using that word right) basically an http based api would work best because, I dont think coding multiple api implementations in different languages is very fun when not that many people will be using it.

**Comment by tycrek** [comment]
A RESTful (I think that's what you were looking for) API is already planned for the future. Each tier will have different levels of access:

- Iron: basic get only
- Gold: detailed get, limited set
- Diamond: full get/set access

With that said, some data will still be inaccessible for security & privacy.

I'm not sure how complex Skynet is so if the above options wouldn't work for it we can also discuss a custom option at some point.
