### ISSUE TITLE
[BUG] login tokens expire very fast with proxy on

### ISSUE THREAD

**Issue by Sand-Turtle** [ttRMS/ttRMS-support#7]
## Describe the bug

ogin tokens expire very fast with proxy on

## How to cause this bug?

1: use the proxy a lot

## What is supposed to happen?

not constantly do it lol

## Additional comments

not too much trouble but annoying as i have to re-enter my password. i use multimc btw

**Comment by jumboman32** [comment]
Ref #8

**Comment by tycrek** [comment]
Probably gonna need to rewrite the auth process but should be fixable

**Comment by tycrek** [comment]
This has been fixed.
