### ISSUE TITLE
[bug] fix permanant inventory desynciing

### ISSUE THREAD

**Issue by Sand-Turtle** [ttRMS/ttRMS-support#9]
## Describe the bug

permanately makes it so you cna only update your inventory in an enderchest until you log. you can move items it seems but nothing happens server side

## How to cause this bug?

have hausemaster shine his deathlly wrath idk

## What is supposed to happen?

I expected it to be able to use my inventory

## Screenshots

(screenshots can be pasted directly into this text box)

**Comment by tycrek** [comment]
This might take time, I'm haven't experienced this myself.

**Comment by tycrek** [comment]
(Resolved over Discord)
